### PR TITLE
First idea how the website can look like. 

### PR DESCRIPTION
**Pull request by vleugelcomplement**
Still missing / unknown: 

- logo / good background image (?)
- FAQ
- Guidelines / code of conduct 
- List of organizers

The template has a nice section with organizers' faces (e.g. https://makezurich.ch/), maybe we can make something similar. Also, there is a section for some selected 'challenges', which can be sessions in our case. 

Regarding dribdat: it would eventually be available on https://live.imprs-astro-hackathon.de, but there are issues with deploying it on a fresh VPS, I'm working on it, but my feeling is that the deadline on Wednesday sounds unrealistic, sorry.

### CODE REVIEW

**Comment by floschulze** [comment]
The deployment of the new website design is not working. Probably we have to change some options for the index file or similar?
@vleugelcomplement  Can you take care of this, you probably know best what to do. If you need more rights for the project or this let me know

**Comment by vleugelcomplement** [comment]
Sure, if you give me the access to the repo settings I would set it up.

**Comment by floschulze** [comment]
Added you as owner of the organisation. I assume that should also give you the admin access to this repo. If not let me know!

**Comment by vleugelcomplement** [comment]
Thanks! The website works now: https://imprs-astro-hackathon.de :)

**Pull request merged**
